AWSTemplateFormatVersion: '2010-09-09'

Description: Lambda to remove resources once budget alert triggered

Resources:
  ExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'azure-devops-ExecutionRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
      Path: '/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: 'budget-lambda-policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowR53
                Effect: Allow
                Action:
                  - 'route53:*'
                Resource: '*'
              - Sid: AllowCloudwatch
                Effect: Allow
                Action:
                  - 'logs:*'
                Resource: '*'

  BudgetAlertTriggeredFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.9
      Role: !GetAtt ExecutionRole.Arn
      Handler: budget_alert_action.lambda_handler
      Timeout: 30
      Code:
        S3Bucket: the-alchemist-cfn
        S3Key: lambda/budget_alert_action.zip
      Tags:
        - Key: Name
          Value: BudgetAlertTriggeredFunction

  BudgetSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !GetAtt BudgetAlertTriggeredFunction.Arn
          Protocol: lambda
      TopicName: TheAlchemistBudgetAlertMonthlyOneDollarExceed

  LambdaFunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt BudgetAlertTriggeredFunction.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !Ref BudgetSNSTopic

Outputs:
  OutputBudgetSNSTopicARN:
    Description: The scale-in policy ARN to use by auto-scale groups with Azure DevOps agents
    Value: !Ref BudgetSNSTopic
    Export:
      Name: BudgetSNSTopicARN
